name: Run Tests and Deploy Allure Report

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: Run tests
        run: mvn clean test
        env:
          p_user: ${{ secrets.P_USER }}
          p_password: ${{ secrets.P_PASSWORD }}
          p_credit_card: ${{ secrets.P_CREDIT_CARD }}
          p_name: ${{ secrets.P_NAME }}
          n_user: ${{ secrets.N_USER }}
          n_password: ${{ secrets.N_PASSWORD }}
          n_credit_card: ${{ secrets.N_CREDIT_CARD }}
          n_name: ${{ secrets.N_NAME }}

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

  deploy-pages:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
